# Generated by Django 5.1 on 2026-06-11 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_User',
            fields=[
                ('user_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='会員ID')),
                ('password', models.CharField(max_length=256, verbose_name='パスワード')),
                ('name', models.CharField(max_length=128, verbose_name='名前')),
                ('address', models.CharField(max_length=256, verbose_name='住所')),
            ],
            options={
                'db_table': 'account_user',
            },
        ),
        migrations.CreateModel(
            name='Administrator_Admin',
            fields=[
                ('admin_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='管理者ID')),
                ('password', models.CharField(max_length=256, verbose_name='パスワード')),
            ],
            options={
                'db_table': 'Administrator_Admin',
            },
        ),
        migrations.CreateModel(
            name='Shopping_Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='カテゴリID')),
                ('name', models.CharField(max_length=256, verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'shopping_category',
            },
        ),
        migrations.CreateModel(
            name='Shopping_Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名')),
                ('manufacturer', models.CharField(max_length=32, verbose_name='メーカー名')),
                ('color', models.CharField(max_length=16, verbose_name='商品の色')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('stock', models.IntegerField(verbose_name='在庫数')),
                ('recommended', models.BooleanField(default=False, max_length=1, verbose_name='オススメ')),
                ('category_id', models.IntegerField(verbose_name='カテゴリID')),
            ],
            options={
                'db_table': 'shopping_item',
            },
        ),
        migrations.CreateModel(
            name='Shopping_Itemsincart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('booked_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shopping_item', verbose_name='商品ID')),
                ('user', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='myapp.account_user', verbose_name='会員ID')),
            ],
            options={
                'db_table': 'Shopping_Itemsincart',
            },
        ),
        migrations.CreateModel(
            name='Shopping_Purchase',
            fields=[
                ('purchase_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='注文ID')),
                ('destination', models.CharField(max_length=256, verbose_name='配送先')),
                ('booked_date', models.DateTimeField(auto_now_add=True, verbose_name='注文日')),
                ('cancel', models.BooleanField(default=False, max_length=1, verbose_name='キャンセル')),
                ('user', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='myapp.account_user', verbose_name='注文者')),
            ],
            options={
                'db_table': 'Shopping_Purchase',
            },
        ),
        migrations.CreateModel(
            name='Shopping_Purchasedetail',
            fields=[
                ('purchase_detail_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='注文詳細ID')),
                ('amount', models.IntegerField(verbose_name='注文数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shopping_item', verbose_name='商品ID')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shopping_purchase', verbose_name='注文ID')),
            ],
            options={
                'db_table': 'Shopping_Purchasedetail',
            },
        ),
    ]
